### ISSUE TITLE
Send To UE | LOD Group

### ISSUE THREAD

**Issue by Hasher95** [poly-hammer/BlenderTools#107]
Addon: Send To UE
Question: How do I export an LOD group as a single file ? I tried several naming convention and it's creating either one file with only one mesh or 3 files with each mesh, I've read the documentation but I'm not sure to understand and there is no example.

Here is the ss of my names
![image](https://github.com/user-attachments/assets/09557e8b-1b2c-46a4-93d4-96e6d694fea7)

And here a ss of my settings 
![image](https://github.com/user-attachments/assets/2835ad10-f42a-419f-bacc-e61dfe8a3221)

I followed this video and it was working without this plugin, but with Send To UE plugin it's no more working even with custom properties enabled.

https://www.youtube.com/watch?v=i_5CU4yYSh0

**Comment by JoshQuake** [comment]
If you're just exporting to disk, then they will save out as separate files. However if you export to project it doesn't really matter as they will properly import into unreal as just the one mesh with LODs.

This might be something to look into when time permits to see if we can combine the meshes when exporting to disk.

**Comment by Hasher95** [comment]
Thanks for the answer ! Hope your updated version detect unreal engine, but I think so. Because the old one no more maintained from epic games wasn't. Anyway if doesn't work I found a workaround and generate LODs inside unreal engine. Thanks again ;)

**Comment by JoshQuake** [comment]
No problem! Closing issue meow
