### ISSUE TITLE
Send to Unreal - Combine children does not respect child transform

### ISSUE THREAD

**Issue by kyleyoungblom** [poly-hammer/BlenderTools#20]
* **Addon:** i.e Send to Unreal
* **OS:** Windows
* **Addon Version:** Send to Unreal 2.4.3
* **Blender Version:** lender 4.1
* **Unreal Version:** Unreal 5.2

Hey there! Really excited that this project is being maintained again. I've had an issue for over a year now where when you export an empty with child meshes, it does not respect the child mesh's rotation.

![image](https://github.com/poly-hammer/BlenderTools/assets/1455464/040795d7-8f48-4318-805a-0eeb302bfdf0)

Originally reported here:
https://github.com/EpicGamesExt/BlenderTools/issues/682

**Comment by jack-yao91** [comment]
Could you make a .zip of that .blend just like you posted above and upload it here?

**Comment by JoshQuake** [comment]
Confirmed the issue. Working on a fix
