### ISSUE TITLE
UE to Rigify - UE5 Mannequin IK broken

### ISSUE THREAD

**Issue by Alfier** [poly-hammer/BlenderTools#21]
IK controllers are not working after conversion. This includes hands, feet, whatsoever

**Addon:** UE to Rigify
* **Steps to Reproduce the Problem:** import UE5 male mannequin FBX skeletal mesh, select root source from 3D view, use "Male Mannequin Ue5" template, click convert. No IK control is working.
* **Error Log:** no error logs
* **OS:** Windows 10
* **Addon Version:** UE2Rigify 1.6.4
* **Blender Version:** Blender 3.6 / 4.1
* **Unreal Version:** Unreal 5.4.2

![Immagine 2024-06-23 130840](https://github.com/poly-hammer/BlenderTools/assets/15878566/01d7c88e-a6f6-4828-88e6-aeeb606679cf)

**Comment by JoshQuake** [comment]
Hey there, I just tested and it is working. It defaults to FK, but there are rig layer controls to switch to IK. Drag this setting to 0 for IK

![image](https://github.com/poly-hammer/BlenderTools/assets/3147154/6a151641-76c2-4c7d-97f4-eda77de7f58c)

Please let me know if those solved the issue.

**Comment by Alfier** [comment]
This solves the issue, thanks. But, since this happens with the standard UE5 mannequin, wouldn't make more sense to default that value to 0?

**Comment by JoshQuake** [comment]
Probably, however those settings are created and handled by Rigify. IMO it's not really feasible to add functionality to change that setting from ue2rigify for specific rigs.

In general, the standard for rigs is defaulting to FK. At least that's what I was taught by my rigging instructor in uni.

@jack-yao91 what do you think?

**Comment by jack-yao91** [comment]
Yea I think if its a debate about the default value, I think FK makes the most sense. I thought the addon will remember your previous state for IK/FK switch you when toggle between modes... At least if that switch value is keyed for your animation it should just pop to that value I think.
