### ISSUE TITLE
Restructure addon folders in repo to take advantage of Blender Script Directories

### ISSUE THREAD

**Issue by jack-yao91** [poly-hammer/BlenderTools#29]
Hi this is a proposal to move the blender addon folder locations into a `src/addons` folder in the repo. This would make development easier because devs can link the addon source code directly to their repo instead of doing the symlink setup like in the [docs](https://poly-hammer.github.io/BlenderTools/contributing/development/#hot-reloading-from-pycharm). That way line tracebacks are correct and debug break points work with a debugger. 

I believe in one of the Blender 3 releases they added this. But I could update the docs to use this instead. The reason we would need to change the repo structure is these require an `addons` sub directory for blender to pick these up.
![image](https://github.com/poly-hammer/BlenderTools/assets/151671689/b74bc584-759b-4174-a895-66f5b693e92c)

Also on another note. How would people feel about me adding a `.vscode` folder to the project for the vscode people? My typical workflow is launch from vscode, then attach to the debugger via debugpy. Would people be oppossed to me making a PR adding this? Also moving the addons into `src/addons`?

Let me know, thanks!

**Comment by JoshQuake** [comment]
I have no issue with that at all. Anything to make our lives easier!

We should prepare for 4.2's addons repo system as well to take advantage of it if we can. Though looks like you need to replace all references to the addon's module with "__package__" which breaks 3.6-4.1...

Alternatively we can say screw the new system and just implement our own check for updates.

**Comment by jack-yao91** [comment]
Yea good point, I can look it that, would be nice if we could get these available on https://extensions.blender.org/
