### ISSUE TITLE
Send2UE Setting Dialog

### ISSUE THREAD

**Issue by youthatninja** [poly-hammer/BlenderTools#30]
Hello, it would be great to change the Settings Dialog menu.
Currently, it's like a minefield, one careless mouse movement and it closes itself.
It is frustrating when you try to carefully set the settings for your export, especially for the first time
Thank you

**Comment by JoshQuake** [comment]
Hehe yeah it's annoying. I think that's just a blender thing tbh but we will see if something can be changed in that regard. Thanks!

**Comment by JoshQuake** [comment]
Hey so I took a look through blender python api and I do not see any way to turn the menu into a actual window, make it static, nor increase the mouse buffer zone around the dialog so it doesnt go away so sudden. The only option would be to recreate the menu as a viewport sidebar panel.

**Comment by JoshQuake** [comment]
Right now we can't really add any priority to this as there is no proper solution so I will close and label as wontfix. However this sounds like a decent beginner project to make an extension that creates the sidebar panel menu suggestion.
