### ISSUE TITLE
Blender Artist Topic / Extensions Blender platform 

### ISSUE THREAD

**Issue by youthatninja** [poly-hammer/BlenderTools#31]
Hi everyone,
I believe it would be beneficial to create a dedicated topic on the Blender Artist forum to facilitate discussion and share updates on the addon's development.

https://blenderartists.org/
Additionally, I'm wondering if there's interest in submitting the addon to the Blender Extensions Platform 
https://extensions.blender.org/

**Comment by jellb** [comment]
Thanks!

**Comment by JoshQuake** [comment]
https://blenderartists.org/t/send-to-unreal-2-4-6-ue-to-rigify-1-7-0-blender-3-6-to-4-2-windows-macos-linux/1541458

BlenderArtists post has been made. Submitting plugins for extensions.blender.org shortly.

**Comment by JoshQuake** [comment]
https://extensions.blender.org/approval-queue/send2ue/
https://extensions.blender.org/approval-queue/ue2rigify/
Submitted extensions for review. Needs more media.

**Comment by JoshQuake** [comment]
Closing out due to platform restrictions that do not allow the functionality of these plugins
