### ISSUE TITLE
USD over FBX

### ISSUE THREAD

**Issue by youthatninja** [poly-hammer/BlenderTools#32]
Hi everyone,
What do you think about switching intermediate data from FBX to USD?
As FBX is a proprietary and maybe outdated format

**Comment by JoshQuake** [comment]
Howdy. I think it would be hard to "compete" with unreals new USD stage editor so I don't think it makes much sense to switch over. I also still prefer FBX 😁

**Comment by jack-yao91** [comment]
At least with how USD is implemented in Unreal the unreal stage editor the API doesn't work super well with how this addon works.

The GLTF 2.0 Blender -> Unreal workflow is now pretty much fully supported with Scene Interchange Framework for StaticMesh, SkeletalMesh, and AnimSequence. I could see that being a possiblity.

You would lose the socket and collision support that the FBX workflow has. Also I would have to check if the StaticMesh and SkeletalMesh editors support importing LODs via gltf. (But I think the materials aren't broken like FBX which would be nice for basic material setups)

Would be a decent amount of work. Mainly copying over all possible settings and making some kinda addon preference to switch to GLTF. And some conditional logic for ingesting LODs (if even possible)

**Comment by JoshQuake** [comment]
For now there's certainly no urgency to make any changes to file format so I will now close as not planned. Worth discussing again in the future, though. Thank you for your time providing the suggestion!
