### ISSUE TITLE
[Send To Unreal] - Strip Numbers from Socket Objects in Multi-Object Files

### ISSUE THREAD

**Issue by wrstldev** [poly-hammer/BlenderTools#36]
This is both a bug or at least unintended behavior and a simple feature request to fix it.

When you have a file with multiple objects, you can't properly create named sockets for them because Blender appends a period and numbers to like named objects. So my first object has a SOCKET_Top which creates a socket named "Top" in my resulting Unreal static mesh, as desired.

But now I create more meshes which also require those named sockets, and I get SOCKET_Top.001, SOCKET_Top.002, SOCKET_Top.003, and so on, which results in my static meshes in Unreal getting sockets named Top.001, Top.002, Top.003 and so on.  Obviously, this is no good, and every mesh should have only a socket named 'Top'. There is no fixing this on Blender's side because they require unique names on all objects (for dictionary lookup) and will instantly add a new trailing number upon removing the old one.

So to fix this I propose a little checkbox on the settings panel that will strip the period and everything after it on sockets while exporting so that every mesh comes into unreal with properly named sockets. With the option checked, Socket_Top.032 becomes "Top" in Unreal for example.
![sockets](https://github.com/user-attachments/assets/63aa0865-74a2-404a-9cd9-749995601c1f)

**Comment by JoshQuake** [comment]
oof that's an oversight that needs corrected for sure. Thanks for the report!
