### ISSUE TITLE
Send2UE - Apply "Use collections as folders" also to Animations (and fwiw Groom)

### ISSUE THREAD

**Issue by eXifreXi** [poly-hammer/BlenderTools#38]
Hey there,

"use collections as folders" currently only seems to work for StaticMesh and SkeletalMesh (as far as I noticed and found in the repo).

Would it be possible to extend this functionality to also work for the other assets that can be exported?
Currently, all Animations will land in the same folder, specified in the Settings Dialog.

I believe I found the part where that is handled in code, but I have no clue about Blender's Addon API, nor am I using python often enough to solve this myself.

Thanks for the work so far.

Cheers!

PS: I just noticed the CONTRIBUTING.md file still points to epicgamesext.

**Comment by eXifreXi** [comment]
Got annoyed by it and had a go at it anyway. Think I got it working.

I looked into your docs and into the page for contributing, and I don't have the time and energy right now to set up testing and create the PR for it.

I did fork the repo and pushed the change to mine, in case someone is interested. I can see if I find the time during the next days to create a proper PR with test and what not.

https://github.com/eXifreXi/BlenderTools/commit/b793176f00498bd904662349824412d9ff38404e

**Comment by JoshQuake** [comment]
Hey thanks for the report and taking a look! Apologies for the lack of response, I've been away for the past few days doing my oh-so-fun yearly medical procedures. I'm back and tired as hell today but I will take a look at what you've figured out and go from there.

**Comment by eXifreXi** [comment]
No worries. Take your time. Health is more important (:
