### ISSUE TITLE
Feature (UEtoRigify): Adding an option for custom template path

### ISSUE THREAD

**Issue by alexander94dmitriev** [poly-hammer/BlenderTools#47]
## Feature
Feature is already implemented: https://github.com/EpicGamesExt/BlenderTools/pull/643
This feature is adding an ability to choose a template path on where to store your rig templates.

It should mitigate an issue when by default templates are stored in Temp folder and once the folder is being cleaned up it also purges your custom templates.
This won't be happening anymore.

It doesn't look like this repository allows pushing the code, so I'm asking if you can create PR yourself and merge this code.
Thank you!

**Comment by JoshQuake** [comment]
Thanks for the suggestion! I was trying to take a look last night but your fork is stuck in migration limbo and can't be accessed. 🤔

**Comment by alexander94dmitriev** [comment]
@JoshQuake hmmm that's the link for PR in original repo. But if you want I can make a fork of the repo with the feature 😄

**Comment by JoshQuake** [comment]
Yes please, I just get the following when trying to look at your changes
![image](https://github.com/user-attachments/assets/76b8cf7c-9f29-4382-865d-91e930765e27)

**Comment by alexander94dmitriev** [comment]
Nevermind, I have managed to create PR :D
https://github.com/poly-hammer/BlenderTools/pull/49
