### ISSUE TITLE
 Send to Unreal wrong scaling. 

### ISSUE THREAD

**Issue by AndrewAlexArt** [poly-hammer/BlenderTools#48]
When send assets to disk and then import them to UE assets has a wrong scale, looks like x100 of original size. Changing pugin export settings not change the scale at all.

Regular Blender export with the same settings don't have such problem and export perfectly. 

* **Addon:** Send to Unreal
* **Steps to Reproduce the Problem:**  Export regular model with settings "Collection as folder enabled":
![Screenshot_1](https://github.com/user-attachments/assets/cd70b241-e380-422e-a342-44dd0cca99de) 

On this screenshot two models with the same export setting one exported manually and second exported with the plugin:
![23](https://github.com/user-attachments/assets/ab99da8a-921e-44fd-b11f-d2c28ef3252d)

* **OS:** Windows
* **Addon Version:** Send to Unreal 2.4.5
* **Blender Version:** Blender 4.1 - 4.2

EDIT2: When import asset to Unity it has the same wrong scale (x100)
![24](https://github.com/user-attachments/assets/8e7bf77b-c830-4f24-8585-2fde02635c8f)

**EDIT3: Looks like I found the bug. If UseObjectOrigin is active the scale goes x100** 
Yep, tested on the fresh project. Very strange place for a bug... Funny thing: even if UseObjectOrigin is not active, objects still use their origin.

**Comment by JoshQuake** [comment]
Thanks for the report! Can you please attach your blend for me?

**Comment by AndrewAlexArt** [comment]
To have the correct scale in Unity, you need to check the Experimental!ApplyTransform option. However, if the UseObjectOrigin option is active, the scale becomes incorrect again in UE and Unity.

Here is an example of the same mesh with these settings with UseObjectOrigin **ENABLED:**
![image](https://github.com/user-attachments/assets/8781fddf-25a1-4b48-83c4-714524c3cdfb)
![image](https://github.com/user-attachments/assets/ec3e588e-36db-4b23-b13e-7acee16ee07c)
![image](https://github.com/user-attachments/assets/c34860f8-3563-4e9f-bca4-a5ffc73369d6)
![image](https://github.com/user-attachments/assets/49e4f943-e6c4-45e9-a3a5-f4974c5667a0)


And UseObjectOrigin **DISABLED:** 
In UE and Unity the scale became normal.
![image](https://github.com/user-attachments/assets/15b97c1b-16a2-4c03-9cc1-fa5d94573958)

![image](https://github.com/user-attachments/assets/5a292a0f-0abc-466c-98bf-04bf49457597)
![image](https://github.com/user-attachments/assets/e44dea6b-3a44-4d3a-9f4c-68934145f4e6)
_Small notice to picture above: if UseObjectOrigin disabled, the origin in Unity not the same as in UE. But it might be Unity feature to always use origin of the object

So I don't know how the plugin works under the hood but UseObjectOrigin option influences on scale of the object

**Comment by JoshQuake** [comment]
Thank you, this should resolve the issue. Not sure why I saw no difference in scale on my first test. The mesh shifted tho. Odd. Anyway, I tested again and you were right.

**Comment by AndrewAlexArt** [comment]
Thank you for supporting this amazing addon!
