### ISSUE TITLE
No module named 'send2ue'

### ISSUE THREAD

**Issue by xiayang09** [poly-hammer/BlenderTools#53]
Appears when installing the plug-in: No module named 'send2ue'
Blender4.2
send2ue2.4.6
![Snipaste_2024-07-31_19-36-25](https://github.com/user-attachments/assets/7aa2e9d0-5727-490a-8826-8e330127d25b)

**Comment by Waldehyd** [comment]
Same here, 2.4.5 works fine

**Comment by JoshQuake** [comment]
argh okay thank you for the report. Worked in testing 😭

**Comment by JoshQuake** [comment]
An update has been released that should resolve this issue. https://github.com/poly-hammer/BlenderTools/releases/tag/20240801230727
