### ISSUE TITLE
Send to Unreal: Policy violation with top level module

### ISSUE THREAD

**Issue by xivader** [poly-hammer/BlenderTools#61]
Hi guys, I've installed the new version of the addon in Blender 4.2 and I recieve this error in the addon tab:

![imagen](https://github.com/user-attachments/assets/64fd3a37-ed68-4435-a245-589b822467e9)

Of course, the Send to Unreal tab doesn't appear in the N panel, although the Pipeline menu does exist.

I'm I missing something on the install?

Same happens with 2.4.6.

**Comment by JoshQuake** [comment]
Those are warnings we need to clean up for Extensions support. The plugin should be working, there is no N panel for Send2UE

**Comment by xivader** [comment]
There's no N panel... true...

Well, thanks anyway!!! You're doing awesome work guys, keep the torch lit!
