### ISSUE TITLE
Send to Unreal - Send to collections seemed to disappear?

### ISSUE THREAD

**Issue by namrog84** [poly-hammer/BlenderTools#65]
Use Collections as folders seems to have disappeared at some point.
I'm upgrading from an older version of both the plugin and blender

This is what I see now
![image](https://github.com/user-attachments/assets/73d5ab0d-1b9e-4443-adb6-3853963a638a)

This is what I used to see

![image](https://github.com/user-attachments/assets/a27de6ae-6b53-4e71-b683-87f0ceec7903)

I'm just assuming this is on me and the setting moved or something. But I'm struggling to find where to enable it.

When I search the code, I see it still exists, and I see others talking about it. So I feel like I'm just overlooking something obvious.

### In the description paste in and edit the following:
* **Addon:** Send to Unreal
* **OS:** Windows
* **Addon Version:** Send to Unreal 2.4.8
* **Blender Version:** Blender 4.2
* **Unreal Version:** N/A

**Comment by namrog84** [comment]
Ah this might be related to the policy violation/compliance work I see mentioned elsewhere.

**Comment by JoshQuake** [comment]
Hey thanks for the report. Interesting. It seems there is some bullshittery in blender 4.2 with how addons load through manual install vs our dev environment. Everything is loading in tests, so I manually installed send2ue 2.4.8 and now extensions don't load. Hmmm.

**Comment by JoshQuake** [comment]
Hey @namrog84 it looks like Jack was able to solve the issue, would you be able to install the zip attached to the PR to verify for us please?

**Comment by namrog84** [comment]
@JoshQuake, I didn't use the zip, but I did apply all the code changes from the PR.

The code in that PR did appear to fix the issue for me.

![image](https://github.com/user-attachments/assets/af712778-36f0-4cc6-9772-cc3882e7d98b)
