### ISSUE TITLE
You have to install ue2rigify to use send2ue otherwise give error AttributeError: 'Scene' object has no attribute 'ue2rigify'

### ISSUE THREAD

**Issue by Genius-pig** [poly-hammer/BlenderTools#75]
### In the description paste in and edit the following:
* **Addon:**  Send to Unreal
* **Steps to Reproduce the Problem:**  I clicked Pipeline > Export > Push assets. But after install ue2rigify, problem solved.
* **Error Log:** Paste the full error log

![931bd52511c00db9065afc36f9fb787](https://github.com/user-attachments/assets/d3ce94a5-84bc-4518-8482-9728b7ef3ae9)

**this annoying warn log still exist**
![image](https://github.com/user-attachments/assets/99736fbf-f07d-41c3-92e0-1a25db12ea17)

* **OS:**  Windows
* **Addon Version:** Send to Unreal 2.4.9
* **Blender Version:** Blender 4.2
* **Unreal Version:** Unreal 5.4.3

**Comment by JoshQuake** [comment]
Heh literally just merged a PR that fixed that. prepping a release right now :)
