### ISSUE TITLE
[BUG] SEND TO UE Can't update number of frames in re-exported animation

### ISSUE THREAD

**Issue by wrstldev** [poly-hammer/BlenderTools#79]
Blender 3.6.1
Send2UE 2.49 (or latest as of this post) I just grabbed the latest release now to double check.
UE 5.4.3

So I have a mesh with a skeleton and an animation. I rough out the animation in 20 frames to get a feel for it. Export to unreal. All is fine.

I decide that the animation needs to be 60 frames instead for pacing reasons. So I set the begin and end frames marker to 1-60 in the action editor, and I move the keyframes so it's a 60 frame animation now. Export.

The animation is stuck at 20 frames. The animation plays, the keys are in the proper places, but it cuts off at frame 20. No matter what it refuses to change the amount of frames.

Deleting the animation completely in unreal and re-exporting with different options (like toggling the 'manual frame range' checkbox, or manually setting the number of frames in the animation viewer) from scratch does not solve the problem, it's forever stuck at 20 frames. 
![bug_frames](https://github.com/user-attachments/assets/c56020ca-8c8c-4411-adfa-eb5e227ea78d)
![bug_frames_range](https://github.com/user-attachments/assets/4d319085-02d4-433d-82e3-78d5a724e9cd)

**Comment by JoshQuake** [comment]
Hey there! I think the NLA strip is still set to 20 frames. I tested by moving a keyframe in this walk animation in the timeline editor, switched to NLA and saw the strip didn't update its range.
![image](https://github.com/user-attachments/assets/f53a0a3a-c24b-48c8-9dce-6684d7d6cd38)
![image](https://github.com/user-attachments/assets/5c27935d-4760-420d-9f70-d1881dc0c4e8)

Please let us know if this solved the issue. If not I'd be happy to take a look at the blend file if you'd like to attach it 
![image](https://github.com/user-attachments/assets/07e12e45-ae22-484e-8345-e50181b8f707)

**Comment by wrstldev** [comment]
FFS, that is the exact issue. 😬

I never see the NLA window because I don't have a use for it. I just use the action editor, and expected that the manual frame range input in the action editor would be honored and was the SAME setting. wtf Blender.

Thanks for clearing this up. I'll close it, but really it should be deleted. Stricken from the record. 😳

**Comment by JoshQuake** [comment]
hehe all good buddy. Glad you got it workin. 👍
