### ISSUE TITLE
UE to Rigify: IK and FK don't seem to be linked

### ISSUE THREAD

**Issue by LakedaemonLive** [poly-hammer/BlenderTools#85]
* **UE to Rigify**
* **Question:**
I checked through the documentation and I think I'm doing everything correctly.  I'm using the UE5 mannequin and Blender 4.2.  I imported the mannequin and ran the UE to Rigify plugin and it seemed like everything worked.  I can move the tweaks and the FK controllers and the mesh does deform.  However, the IK controls don't move the mesh.  Also, when I go back to edit mode, even though the Mesh is deformed the Rigify rig bones seem to still be in the A pose and haven't appeared to move.  I'm assuming there is a linking through constraints that doesn't seem to be working.  However, I have looked through the constraints and I do see some linking, but I'll be honest.  I'm not expert enough to know if it is right or not.

Hope someone might have some ideas of what to check or of any steps I might have missed!

Thought it might help to add my blend file (didn't think I could add it when editing a posted issue so apologies for extra):

[UE5MannyImportedSuccessfully.zip](https://github.com/user-attachments/files/17102489/UE5MannyImportedSuccessfully.zip)

**Comment by LakedaemonLive** [comment]
Thought it might help to add my blend file:

[UE5MannyImportedSuccessfully.zip](https://github.com/user-attachments/files/17102481/UE5MannyImportedSuccessfully.zip)

**Comment by JoshQuake** [comment]
Select a hand/foot to see the IK/FK toggle
![image](https://github.com/user-attachments/assets/fa31a5fb-fcb7-4643-9c64-51fae3c4e893)
