### ISSUE TITLE
cant make more than two templates

### ISSUE THREAD

**Issue by abehloul** [poly-hammer/BlenderTools#89]
hello,

edit: regarding ue2rigify
after creating two templates, I have to delete one the add a third

I have been facing this issue since the old version on blender 3.6
even after update the issue persists

the workaround was to move the templates out of the template file then create a new one before placing the olds back
but it would be great if we could just create the templates directly

so is there a way to fix this, or am I doing something wrong, or is it a bug?

**Comment by jack-yao91** [comment]
Is the related to send2ue or ue2rigify addon?

**Comment by abehloul** [comment]
sorry for not precising,
this is related to ue2rigify

**Comment by JoshQuake** [comment]
@jack-yao91 LMK if you would like me to take a look at this.

**Comment by abehloul** [comment]
here is a small demonstration of what Im talking about, as I cannot have more that four templates

https://github.com/user-attachments/assets/7c8cafc3-8893-400f-ae5e-41c70adba75d

**Comment by jack-yao91** [comment]
@JoshQuake That would be much appreciated 🙏

**Comment by JoshQuake** [comment]
@jack-yao91 okok I shall. @abehloul gotcha thanks!

**Comment by JoshQuake** [comment]
Released [UE2Rigify 1.7.3](https://github.com/poly-hammer/BlenderTools/releases/tag/20241008211717) with a fix
