### ISSUE TITLE
Re-Report a bug that has been issued in official branch #756

### ISSUE THREAD

**Issue by DaqiHu** [poly-hammer/BlenderTools#97]
Hi, I'm new to this branch and thank you for all of your contributions to make `Send2UE` available to Unreal 5.4 and Blender 4.2. 

I've encountered a bug that when exporting textures with an auto-generated prefix (`T_`), those files will be missing the next time you open Blender.

For more details please check this issue I created in the official branch:

https://github.com/EpicGamesExt/BlenderTools/issues/756

**Comment by JoshQuake** [comment]
Thank you for the report! There is a little bit of a lineup all of a sudden so I will try get to you as soon as I can.
